FROM rancher/k3s:v0.8.1

# FROM alpine:3.10.2
# SHELL ["/bin/ash", "-eo", "pipefail", "-c"]

# RUN apk --no-cache add --update \
#   curl=7.65.1-r0

# RUN apk --no-cache add --update --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing \
#   k3s=0.8.1-r0


# RUN curl -sfL https://get.k3s.io | sh -

# FROM ubuntu:19.10
# SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# RUN apt-get update && apt-get -y --no-install-recommends install \
#   curl=7.65.3-1ubuntu1 \
#   ca-certificates=20190110 \
#   systemd=240-6ubuntu9 \
#   && apt-get clean \
#   && rm -rf /var/lib/apt/lists/*

# RUN curl -sfL https://get.k3s.io | sh -