name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and push
        uses: ./.github/actions/main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration:
    steps:
      - name: First
        run: which k3s
    services:
      k3s:
        image: rancher/k3s:v0.8.1
        command: server --disable-agent
        environment:
        - K3S_CLUSTER_SECRET=somethingtotallyrandom
        - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
        - K3S_KUBECONFIG_MODE=666
        volumes:
        - k3s-server:/var/lib/rancher/k3s
        - .:/output
        ports:
        - 6443:6443
        node:
    container:
      image: rancher/k3s:v0.8.1
      tmpfs:
        - /run
        - /var/run
      environment:
        - K3S_URL=https://server:6443
        - K3S_CLUSTER_SECRET=somethingtotallyrandom
        # Can also use K3S_TOKEN from /var/lib/rancher/k3s/server/node-token instead of K3S_CLUSTER_SECRET
        #- K3S_TOKEN=K13849a67fc385fd3c0fa6133a8649d9e717b0258b3b09c87ffc33dae362c12d8c0::node:2e373dca319a0525745fd8b3d8120d9c

            
